### ISSUE TITLE
Caffe2->ONNX model checker error. Unrecognized attribute: is_test in dropout layer

### ISSUE THREAD

**Issue by inkawhich** [onnx/onnx#1071]
I am trying to run a very simple extension of the Caffe2OnnxExport tutorial. I am using the init/predict_net.pb files for squeezenet from Caffe2's Model Zoo for the export. However, the checker is giving an error on the dropout layer for the is_test attribute. My entire code is here:

```
import onnx
import caffe2.python.onnx.frontend
from caffe2.proto import caffe2_pb2

inet = "models/squeezenet/init_net.pb"
pnet = "models/squeezenet/predict_net.pb"

# We need to provide type and shape of the model inputs
data_type = onnx.TensorProto.FLOAT
data_shape = (1, 3, 224, 224)
value_info = { 'data': (data_type, data_shape) }

# Prepare the nets
predict_net = caffe2_pb2.NetDef()
with open(pnet, 'rb') as f:
    predict_net.ParseFromString(f.read())

init_net = caffe2_pb2.NetDef()
with open(inet, 'rb') as f:
    init_net.ParseFromString(f.read())

# Make sure the net has a name. Otherwise, the checker will fail.
if predict_net.name == "":
    predict_net.name = "ModelNameHere"

# Create the ONNX model
onnx_model = caffe2.python.onnx.frontend.caffe2_net_to_onnx_model(
    predict_net,
    init_net,
    value_info,
)

# Check the ONNX model
onnx.checker.check_model(onnx_model)

# Save the ONNX model
onnx.save(onnx_model, 'models/squeezenet/my_squeezenet.onnx')

```

and the error is here:

```
W0603 11:47:35.521780 2950550336 onnx_exporter.cc:491] Converting legacy padding to explicit padding.
W0603 11:47:35.524869 2950550336 onnx_exporter.cc:491] Converting legacy padding to explicit padding.
W0603 11:47:35.527192 2950550336 onnx_exporter.cc:491] Converting legacy padding to explicit padding.
Traceback (most recent call last):
  File "caffe2_to_onnx.py", line 30, in <module>
    value_info,
  File "/Users/nateinkawhich/pytorch/caffe2/python/onnx/frontend.py", line 332, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/Users/nateinkawhich/pytorch/caffe2/python/onnx/frontend.py", line 268, in caffe2_net_to_onnx_graph
    checker.check_graph(graph_def)
  File "/Users/nateinkawhich/onnx/onnx/checker.py", line 51, in checker
    proto.SerializeToString(), ctx)
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: is_test

==> Context: Bad node spec: input: "fire9/concat_1" output: "fire9/concat_2" output: "_fire9/concat_mask_1" name: "" op_type: "Dropout" attribute { name: "ratio" f: 0.5 type: FLOAT } attribute { name: "is_test" i: 1 type: INT }
```

Is there a simple fix for this error?

I am running on a Mac and built onnx from source with

```
python setup.py build develop
```

Thanks,
Nate

**Comment by inkawhich** [comment]
Also, when I try using *bvlc_alexnet* I get a similar error with broadcast

```
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: broadcast

==> Context: Bad node spec: input: "OC2_DUMMY_0" input: "fc6_w_0" input: "fc6_b_0" output: "fc6_1" op_type: "Gemm" attribute { name: "transB" i: 1 type: INT } attribute { name: "broadcast" i: 1 type: INT }
```

**Comment by bddppq** [comment]
This looks weird, because caffe2 is exporting to opset 6, and Dropout should have `is_test` attribute (so does Gemm for `broadcast`). Could you do `print(onnx_model.opset_import)` (before invoking checker)?

**Comment by bddppq** [comment]
Oh I just noticed it's check_graph being problematic, which has been fixed in https://github.com/pytorch/pytorch/commit/f9633b954268c493dabfe7c2047f9331cb4a621e around a week ago, could you build caffe2 from source from current master?

**Comment by inkawhich** [comment]
Just synced my pytorch repo with current version and rebuilt pytorch, caffe2, onnx, and I am still getting this same error.

**Comment by bddppq** [comment]
@inkawhich Are you sure you got the same error? Because in current pytorch/caffe2 master I couldn't find anywhere calling check_graph.

**Comment by inkawhich** [comment]
I was rebuilding incorrectly, this issue is resolved.  Thanks for the help!
