### ISSUE TITLE
onnx build script always depends on python2

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#1314]
OS: fedora 27
build steps:
```bash
dnf install -y curl eigen3-devel gcc gcc-c++ zlib-devel cmake make ninja-build git python3-devel python3-numpy libunwind icu aria2 rsync python3-setuptools python3-wheel
export ONNX_ML=1
aria2c --download-result=hide -d /tmp/src  https://github.com/onnx/onnx/archive/v1.2.2.tar.gz
tar -xf /tmp/src/onnx-1.2.2.tar.gz -C /tmp/src
cd /tmp/src/onnx-1.2.2
python3 setup.py  bdist_wheel
```
output:
```
[  5%] Running C++ protocol buffer compiler on /tmp/src/onnx-1.2.2/.setuptools-cmake-build/onnx/onnx-ml.proto
/usr/bin/env: ‘python’: No such file or directory
--mypy_out: protoc-gen-mypy: Plugin failed with status code 127.
gmake[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:62: onnx/onnx-ml.pb.cc] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/gen_onnx_proto.dir/all] Error 2
gmake: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 327, in <module>
    'backend-test-tools = onnx.backend.test.cmd_tools:main',
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 199, in run
    self.run_command('build')
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 202, in run
    self.run_command('cmake_build')
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 196, in run
    subprocess.check_call(build_args)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/cmake3', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
```

I haven't installed python 2. I only have python3. Therefore I cannot build onnx.

**Comment by houseroad** [comment]
Shouldn't we always have a python executable, either link to python2 or python3?

**Comment by snnn** [comment]
@houseroad On Centos and Fedora, /usr/bin/python is always linked to python2. If you don't have python2 installed, then you won't have this link.

**Comment by cjtang** [comment]
I also meet this problem with python2. Is there any solution?

**Comment by Sem-Kulish** [comment]
@cjtang Solved this by cp /usr/bin/python3 /usr/bin/python

**Comment by houseroad** [comment]
or using `ln` instead of `cp`

**Comment by snnn** [comment]
@xental A lot of system applications(like yum) depends on python, if you do that, you will break them.

**Comment by EmmaW8** [comment]
I met same problem.
So how to solve it? my python is from anaconda 3

**Comment by trohit920** [comment]
@xental I got this error while build onnx.
 `running install
running bdist_egg
running egg_info
creating onnx.egg-info
writing requirements to onnx.egg-info/requires.txt
writing onnx.egg-info/PKG-INFO
writing top-level names to onnx.egg-info/top_level.txt
writing dependency_links to onnx.egg-info/dependency_links.txt
writing entry points to onnx.egg-info/entry_points.txt
writing manifest file 'onnx.egg-info/SOURCES.txt'
reading manifest file 'onnx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running create_version
running cmake_build
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
CMake Warning at CMakeLists.txt:365 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11"
  (requested version 2.2) with any of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- 
-- ******** Summary ********
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   CXX flags             :  -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : 
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : 
-- 
--   ONNX version          : 1.5.0
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
-- 
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf includes     : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
--   BUILD_ONNX_PYTHON     : ON
--     Python version      : 
--     Python executable   : /usr/bin/python
--     Python includes     : /usr/include/python2.7
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rohit/onnx/.setuptools-cmake-build
Scanning dependencies of target onnxifi_loader
Scanning dependencies of target gen_onnx_proto
Scanning dependencies of target onnxifi_dummy
[  1%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
[  3%] Running gen_proto.py on onnx/onnx.in.proto
[  5%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
Processing /home/rohit/onnx/onnx/onnx.in.proto
Writing /home/rohit/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Writing /home/rohit/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
/home/rohit/onnx/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
/home/rohit/onnx/onnx/onnxifi_dummy.c:173:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
           *function = &onnxGetExtensionFunctionAddress;
                     ^
/home/rohit/onnx/onnx/onnxifi_dummy.c:176:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
           *function = &onnxSetIOAndRunGraph;
                     ^
generating /home/rohit/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
[  7%] Running C++ protocol buffer compiler on /home/rohit/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
[  8%] Linking C static library libonnxifi_loader.a
[ 10%] Linking C shared library libonnxifi_dummy.so
[ 10%] Built target onnxifi_loader
Scanning dependencies of target onnxifi_wrapper
[ 12%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
[ 12%] Built target onnxifi_dummy
Traceback (most recent call last):
  File "/home/rohit/onnx/tools/protoc-gen-mypy.py", line 367, in <module>
    main()
  File "/home/rohit/onnx/tools/protoc-gen-mypy.py", line 354, in main
    generate_mypy_stubs(Descriptors(request), response)
  File "/home/rohit/onnx/tools/protoc-gen-mypy.py", line 296, in generate_mypy_stubs
    pkg_writer.write_messages(fd.message_type, "")
  File "/home/rohit/onnx/tools/protoc-gen-mypy.py", line 178, in write_messages
    if msg.options.map_entry:
AttributeError: 'MessageOptions' object has no attribute 'map_entry'
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
CMakeFiles/gen_onnx_proto.dir/build.make:61: recipe for target 'onnx/onnx-ml.pb.cc' failed
make[2]: *** [onnx/onnx-ml.pb.cc] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/gen_onnx_proto.dir/all' failed
make[1]: *** [CMakeFiles/gen_onnx_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 14%] Linking C shared module libonnxifi.so
[ 14%] Built target onnxifi_wrapper
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 331, in <module>
    'backend-test-tools = onnx.backend.test.cmd_tools:main',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 206, in run
    self.run_command('cmake_build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 200, in run
    subprocess.check_call(build_args)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/usr/bin/cmake', u'--build', '.', u'--', u'-j', '8']' returned non-zero exit status 2
`
Is this onnx issue or protobuf? Any help will be highly appreciated.

**Comment by snnn** [comment]
It can be fixed by removing the shebang and invoking python explicitly

**Comment by trohit920** [comment]
@snnn I still getting the same error as before.

**Comment by nopattern** [comment]
me too for python2 ,and python3.

**Comment by wschin** [comment]
+1

**Comment by vinitra** [comment]
The root cause of this issue has been resolved. PR: https://github.com/onnx/onnx/pull/2452

**Comment by snnn** [comment]
I don't think so.  https://github.com/onnx/onnx/blob/master/tools/mypy-onnx.py is unchanged.

**Comment by snnn** [comment]
I guess it's not fixed. 

The solution should be: instead of find python by
```bash
#!/usr/bin/env python
```
It should use the value of cmake variable "Python_EXECUTABLE"

**Comment by Kammmil** [comment]
@trohit920 
Did you solve it somehow and if yes please share the solution :)

**Comment by jcwchen** [comment]
It should be resolved by https://github.com/onnx/onnx/pull/2961. Please reopen it if you still encounter this issue. Thank you!
