### ISSUE TITLE
SequenceInsert backend test throws ValueError: Currently not supporting loading segments.

### ISSUE THREAD

**Issue by chinhuang007** [onnx/onnx#2984]
# Bug Report

### Describe the bug
The SequenceInsert backend test has two inputs, a sequence and a tensor. The test runner seems to work with only Tensor type, not Sequence type, as seen in https://github.com/onnx/onnx/blob/25fd2c332cf854fd38a92aa8f60d232530ab0065/onnx/backend/test/runner/__init__.py#L298. The error occurs at numpy_helper.to_array(tensor) because the tensor is actually a SequenceProto not a TensorProto in test data input_0.pb

### System information
- OS Platform and Distribution: Ubuntu 18.04 
- ONNX version: 1.7 (master) 
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source): 8.3.0
- CMake version: 3.17.3
- Protobuf version: 3.11.3

### Expected behavior
Test runner should have a way to load inputs and outputs in SequenceProto differently from TensorProto

### Notes
Would be nice to be able to catch this kind of errors in ONNX CI

**Comment by askhade** [comment]
This is a known limitation right now. At the time the use case was only for Sequences of Tensors. The infra needs to be extended to support Sequences of Sequences or Sequences of say Maps.

You are welcome to add a PR for this :)

**Comment by jcwchen** [comment]
I believe it has been resolved by this https://github.com/onnx/onnx/pull/3136. Please reopen it if I am wrong. Thank you.

**Comment by EasonChow001** [comment]
@chinhuang007  hi，i meet relevant failure, i still not know how to fix it. look [this](https://github.com/microsoft/onnxruntime/issues/7143).
