### ISSUE TITLE
 ONNX 1.15.0 failing to install on Linux

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx#5716]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
When installing ONNX 1.15.0 on a Jenkins Node I receive the following build errors but only for Linux, it passes fine for MacOS amd64:

```
[100%] Built target onnx_cpp2py_export
      copying /workdir/onnx-mlir/third_party/onnx/.setuptools-cmake-build/onnx_cpp2py_export.cpython-310-x86_64-linux-gnu.so -> build/lib.linux-x86_64-3.10/onnx
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 327, in <module>
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "setup.py", line 265, in run
          return super().run()
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "setup.py", line 294, in build_extensions
          if self.editable_mode:
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: editable_mode
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for UNKNOWN
Failed to build UNKNOWN
```

### Reproduction instructions
```
1. Match the same requirements
2. Install ONNX 1.15.0 on Linux amd64/ Linux ppc64le/ Linux s390x
```

### Expected behavior
Expect ONNX 1.15.0 to build successfully. 

### Notes
In the stack trace above, I see the following:
`Failed building wheel for UNKNOWN`
I have never seen this before for other ONNX's versions.

**Comment by gramalingam** [comment]
@liqunfu

**Comment by Ichimikichiki** [comment]
```
[ 97%] Linking CXX static library libonnx.a
[ 97%] Built target onnx
[ 98%] Building CXX object CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o
[100%] Linking CXX shared module onnx_cpp2py_export.cpython-39-x86_64-linux-gnu.so
/bin/ld: /usr/local/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/build.make:101: onnx_cpp2py_export.cpython-39-x86_64-linux-gnu.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:223: CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by justinchuby** [comment]
Please make sure the `setuptools` in the environment is up to date.

**Comment by liqunfu** [comment]
> Please make sure the `setuptools` in the environment is up to date. You should also use `pip install -e .` for editable mode installs, and use `python -m build` for building wheels. @liqunfu we should call this out in the release notes

done

**Comment by hamptonm1** [comment]
@justinchuby This is not closed nor completed.... my builds are still failing. I was away for a week so could not respond.

**Comment by hamptonm1** [comment]
We are already using `pip install -e .`.... For me to get past the initial error, I had to upgrade setuptools as well as pip. However, we now run into a new error, as I mentioned before we never had these issues for any prior release of ONNX. 

```
Traceback (most recent call last):
  File "/workdir/onnx-mlir/build/docs/doc_example/gen_add_onnx.py", line 1, in <module>
    import onnx
  File "/usr/local/lib64/python3.9/site-packages/onnx/__init__.py", line 75, in <module>
    from onnx import serialization
  File "/usr/local/lib64/python3.9/site-packages/onnx/serialization.py", line 16, in <module>
    import google.protobuf.json_format
  File "/usr/local/lib64/python3.9/site-packages/protobuf-3.20.3-py3.9-linux-x86_64.egg/google/protobuf/json_format.py", line 54, in <module>
    from google.protobuf.internal import type_checkers
  File "/usr/local/lib64/python3.9/site-packages/protobuf-3.20.3-py3.9-linux-x86_64.egg/google/protobuf/internal/type_checkers.py", line 51, in <module>
    from google.protobuf.internal import decoder
  File "/usr/local/lib64/python3.9/site-packages/protobuf-3.20.3-py3.9-linux-x86_64.egg/google/protobuf/internal/decoder.py", line 87, in <module>
    from google.protobuf.internal import encoder
  File "/usr/local/lib64/python3.9/site-packages/protobuf-3.20.3-py3.9-linux-x86_64.egg/google/protobuf/internal/encoder.py", line 71, in <module>
    from google.protobuf.internal import wire_format
  File "/usr/local/lib64/python3.9/site-packages/protobuf-3.20.3-py3.9-linux-x86_64.egg/google/protobuf/internal/wire_format.py", line 36, in <module>
    from google.protobuf import descriptor
  File "/usr/local/lib64/python3.9/site-packages/protobuf-3.20.3-py3.9-linux-x86_64.egg/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: libprotobuf.so.31: cannot open shared object file: No such file or directory
make[2]: *** [docs/doc_example/CMakeFiles/OMRuntimeTestModel.dir/build.make:73: docs/doc_example/libadd.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:11928: docs/doc_example/CMakeFiles/OMRuntimeTestModel.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

The solution is not to upgrade protobuf because when I did so (4.21.12 to match what you guys have), I still had the same error..... only for Linux if I need to be exact. 


```
[ 96%] Generating libadd.so

/usr/local/lib64/python3.9/site-packages/protobuf-4.21.12-py3.9-linux-x86_64.egg/google/protobuf/internal/api_implementation.py:109: UserWarning: Selected implementation cpp is not available.

  warnings.warn(

Traceback (most recent call last):

  File "/workdir/onnx-mlir/build/docs/doc_example/gen_add_onnx.py", line 1, in <module>

    import onnx

  File "/usr/local/lib64/python3.9/site-packages/onnx/__init__.py", line 75, in <module>

    from onnx import serialization

  File "/usr/local/lib64/python3.9/site-packages/onnx/serialization.py", line 16, in <module>

    import google.protobuf.json_format

  File "/usr/local/lib64/python3.9/site-packages/protobuf-4.21.12-py3.9-linux-x86_64.egg/google/protobuf/json_format.py", line 54, in <module>

    from google.protobuf.internal import type_checkers

  File "/usr/local/lib64/python3.9/site-packages/protobuf-4.21.12-py3.9-linux-x86_64.egg/google/protobuf/internal/type_checkers.py", line 51, in <module>

    from google.protobuf.internal import decoder

  File "/usr/local/lib64/python3.9/site-packages/protobuf-4.21.12-py3.9-linux-x86_64.egg/google/protobuf/internal/decoder.py", line 87, in <module>

    from google.protobuf.internal import encoder

  File "/usr/local/lib64/python3.9/site-packages/protobuf-4.21.12-py3.9-linux-x86_64.egg/google/protobuf/internal/encoder.py", line 71, in <module>

    from google.protobuf.internal import wire_format

  File "/usr/local/lib64/python3.9/site-packages/protobuf-4.21.12-py3.9-linux-x86_64.egg/google/protobuf/internal/wire_format.py", line 36, in <module>

    from google.protobuf import descriptor

  File "/usr/local/lib64/python3.9/site-packages/protobuf-4.21.12-py3.9-linux-x86_64.egg/google/protobuf/descriptor.py", line 51, in <module>

    from google.protobuf.pyext import _message

ImportError: libprotobuf.so.32: cannot open shared object file: No such file or directory

make[2]: *** [docs/doc_example/CMakeFiles/OMRuntimeTestModel.dir/build.make:73: docs/doc_example/libadd.so] Error 1

make[1]: *** [CMakeFiles/Makefile2:11928: docs/doc_example/CMakeFiles/OMRuntimeTestModel.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

[ 96%] Linking CXX shared module ../../Release/lib/PyCompile.cpython-39-x86_64-linux-gnu.so

[ 96%] Linking CXX shared module ../../Release/lib/PyCompileAndRuntime.cpython-39-x86_64-linux-gnu.so

[ 96%] Built target PyCompile

[ 96%] Built target PyCompileAndRuntime

[ 96%] Linking CXX shared library ../../Release/lib/libModelLib.so

[ 96%] Built target ModelLib

make: *** [Makefile:146: all] Error 2
```

**Comment by justinchuby** [comment]
Do you have libprotobuf installed on your machine? If so does setting -DONNX_USE_PROTOBUF_SHARED_LIBS=ON help?

**Comment by hamptonm1** [comment]
> Do you have libprotobuf installed on your machine? If so does setting -DONNX_USE_PROTOBUF_SHARED_LIBS=ON help?

I am actually doing so now... I added an `apt-get install libprotobuf-dev` to see if that will work. It says the missing file is being installed according to the build logs:

```
libtool: install: /usr/bin/install -c .libs/libprotobuf.so.31.0.3 /usr/local/lib/libprotobuf.so.31.0.3
libtool: install: (cd /usr/local/lib && { ln -s -f libprotobuf.so.31.0.3 libprotobuf.so.31 || { rm -f libprotobuf.so.31 && ln -s libprotobuf.so.31.0.3 libprotobuf.so.31; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libprotobuf.so.31.0.3 libprotobuf.so || { rm -f libprotobuf.so && ln -s libprotobuf.so.31.0.3 libprotobuf.so; }; })
```

Hopefully we can get onnx installed correctly. Thanks

**Comment by hamptonm1** [comment]
@justinchuby Unfortunately I am still getting the same error message when installing libprotobuf and using `-DONNX_USE_PROTOBUF_SHARED_LIBS=ON `

**Comment by hamptonm1** [comment]
@justinchuby I figured out the issue and was able to resolve it. I will close this out for now. Thank you!

**Comment by yujunsun110** [comment]
> @justinchuby I figured out the issue and was able to resolve it. I will close this out for now. Thank you!

I am facing the same problem here, would you share how you solved this?

**Comment by KevinJBoyer** [comment]
@yujunsun110 IAN @hamptonm1, but after finding this thread, I realized I was trying to install a version of ONNX (1.14.1, so different from this issues original title!) that was not supported on the version of Python I was running (3.12). I used `pyenv` to switch to `3.10.10` and that fixed it.
