### ISSUE TITLE
Grepability of tests in Onnx Backend test framework

### ISSUE THREAD

**Issue by anirudhacharya** [onnx/onnx#593]
Has the following test been misnamed -
https://github.com/onnx/onnx/blob/910db3bcd94e737fc0b497a1ac4b9f7028595a82/onnx/backend/test/case/node/slice.py#L84-L97
Shouldn't it be test_slice_default_axes instead of test_default_axes because if I do
```python
onnx_backend_test.include("test_slice*") 
```
the 'default_axes' test will not be included. Was this a mistake in 
naming the test. I can raise a PR to fix this.

Also while including tests there is the following issue -
The following command
```python
onnx_backend_test.include("test_squeeze")  #**(without an asterisk)**
```
ends up including two test cases
- test_squeeze
- test_squeezenet_cpu
whereas I need to run only the first test for the squeeze operator.
(https://github.com/onnx/onnx/blob/910db3bcd94e737fc0b497a1ac4b9f7028595a82/onnx/backend/test/case/node/squeeze.py#L16-L27)

**Comment by houseroad** [comment]
Good catch on the name. Fixed here: https://github.com/onnx/onnx/pull/596

For the second case, you can add '$' to your regex to make the condition more restrict.

**Comment by anirudhacharya** [comment]
@houseroad  Thanks for the first fix.

The second one still does not work. If I use the following
```python
onnx_backend_test.include("test_squeeze$")
```
It matches neither of the two test cases -
* test_squeeze
* test_squeezenet_cpu

**Comment by houseroad** [comment]
I guess you have two cases, test_squeeze_cpu and test_squeezenet_cpu, can you try:
```
onnx_backend_test.include("test_squeeze_")
```

**Comment by anirudhacharya** [comment]
@houseroad Thanks, that works in the above case.

But I am still unclear about how the regex is working. For instance
Regex => "test_log_" matches the following two test cases -
* test_log_cpu
* test_log_example_cpu

Regex => "test_log_*" is matching the following (two + six) test cases -
* test_log_cpu
* test_log_example_cpu
* test_logsoftmax_axis_0_cpu
* test_logsoftmax_axis_1_cpu
* test_logsoftmax_axis_2_cpu
* test_logsoftmax_default_axis_cpu
* test_logsoftmax_example_1_cpu
* test_logsoftmax_large_number_cpu

So what is the '*' character doing? It does not seem like it is a just a wildcard match like in most regular expressions.

**Comment by houseroad** [comment]
_* matches any string which only contains "_", such as empty string, "_", "__", "___".

I guess what you want is test_log_.*

**Comment by anirudhacharya** [comment]
Thank you.
